sudo: required
dist: trusty
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7638D0442B90D010
  - sudo su -c 'echo deb http://http.us.debian.org/debian/ experimental main contrib non-free >> /etc/apt/sources.list'
  - sudo apt-get -y update
  - apt-cache policy libgnutls28-dev
  - sudo apt-get -y install libgnutls28-dev/experimental
addons:
  apt:
    packages:
    - libgpgme11-dev
    - libio-socket-ssl-perl
    - libipc-run-perl
    - valgrind
    - ltrace

language: c
compiler: gcc

script:
  - make test
