sudo: required
dist: trusty
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7638D0442B90D010
  - sudo su -c 'echo deb http://httpredir.debian.org/debian/ experimental main contrib non-free >> /etc/apt/sources.list'
  - sudo su -c 'echo deb http://httpredir.debian.org/debian/ sid main contrib non-free >> /etc/apt/sources.list'
  - sudo apt-get -y update
  - sudo dpkg --purge --force-depends libcurl4-gnutls-dev libgnutls-dev librtmp-dev
  - sudo apt-get -y -f -t experimental install gnutls-bin libgnutls28-dev libgnutls-openssl27 libidn11-dev libgmp10 libp11-kit0 libtasn1-6
addons:
  apt:
    packages:
    - libgpgme11-dev
    - libio-socket-ssl-perl
    - libipc-run-perl
    - valgrind
    - ltrace

language: c
compiler: gcc

script:
  - make test
