sudo: required
dist: trusty
before_install:
  - sudo apt-get -y install libgnutls28-dev
addons:
  apt:
    packages:
    - libgpgme11-dev
    - libio-socket-ssl-perl
    - libipc-run-perl
    - valgrind

language: c
compiler: gcc

script:
  - make test
