ihlt : ConnectionsDoublyLinkedList.o protocol.o server.o

ConnectionsDoublyLinkedList.o : ConnectionsDoublyLinkedList.h

protocol.o : protocol.h

server.o : server.h

clean:
	rm -f *.o ihlt

.PHONY: clean
